### ISSUE TITLE
Support for private git repositories

### ISSUE THREAD

**Issue by almereyda** [turbot/steampipe-plugin-config#38]
**Is your feature request related to a problem? Please describe.**

When wanting to parse and query data stored in config files in git repositories, this data is found in private repositories on GitLab or GitHub. Accessing those is currently not possible, in difference to accessing private S3 buckets.

**Describe the solution you'd like**
Both and other git hosting services provide token or SSH authentication possibilities. These were to leverage for implementing a "standard-compliant" way to allow git authentication.

**Describe alternatives you've considered**
This is a one-way street. There's no alternative to that, when wanting to support private git repositories.

**Additional context**
ArgoCD offers nice abstractions for managing git repository access & credentials.

- https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repository-credentials

**Comment by Subhajit97** [comment]
Hi @almereyda! Thanks for using Steampipe and the Config plugin. Apologies for the inconvenience.

Our SDK uses the [hashicorp/go-getter](https://github.com/hashicorp/go-getter) package to retrieve files from Git, S3, and other remote sources. If you're referring to the URL style, passing in SSH style URLs should also work according to the [go-getter README](https://github.com/hashicorp/go-getter#git-git). For example, if you are trying to query a private repository, using the `paths` format like below should work if you have access to that repository:
```hcl
connection "config" {
  plugin = "config"

  # Format should be similar for INI and YAML as well
  json_paths =  [ "git::ssh://git@github.com/<user>/<repo>//*.json" ]
}
```

If you see any different results, please let us know what your paths arg is set to and what the unexpected results are, and then we can troubleshoot more.

**Comment by misraved** [comment]
Hey @almereyda, We are closing this issue because we have not heard from you. Please feel free to reopen the issue if you want to share or discuss anything.
